version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./mobile
      dockerfile: Dockerfile
    ports:
      - "19006:19006"
    volumes:
      - ./mobile:/app

  db:
    image: postgres
